ObjectInstantiationException: updated to expose the underlying 'cause' excpetion.
Issue 3053473

git-svn-id: http://svn.code.sf.net/p/htmlunit/code/trunk@5957 5f5364db-9458-4db8-a492-e30667be6df6